version: '3.4'

x-common-variables: &common-variables
  DATABASE_HOST: db
  MYSQL_DATABASE: shareholders
  MYSQL_USER: shareholderUser1
  MYSQL_PASSWORD: password
  SERVER_PORT: 8080

services:
  db:
    build: ./db
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: password
  server:
    build: ./server
    environment:
      <<: *common-variables
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure